[package]
edition = "2018"
name = " rust-embedded-starter"
version = "0.2.0"

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.14"
stm32f3-discovery = "0.7.0"
panic-itm = "0.4.2"


[profile.release]
codegen-units = 1
debug = true
lto = true
